export const simulatedManagerCases = [
  {
    id: "sim_delta_logistics",
    caseCode: "SIM-DELTA-001",
    title: "Delta Logistics — Fleet Insurance Renewal",
    clientCompanyName: "Delta Logistics",
    brokerName: "Apex Risk Brokers",
    insuranceType: "Fleet Insurance",
    currentTeam: "finance",
    currentBlockName: "Premium Reconciliation",
    currentStatus: "WAITING",
    expectedPremium: "₹18L",
    monthEndPriority: true,
    businessImpact: "Premium blocked before month-end closure",
    source: "simulated" as const,
  },
  {
    id: "sim_nova_infra",
    caseCode: "SIM-NOVA-002",
    title: "Nova Infra — Project Liability Quote",
    clientCompanyName: "Nova Infra",
    brokerName: "MetroSure Brokers",
    insuranceType: "Project Liability",
    currentTeam: "policyIssuance",
    currentBlockName: "Policy QA Correction",
    currentStatus: "BLOCKED",
    expectedPremium: "₹25L",
    monthEndPriority: true,
    businessImpact: "Policy issuance delayed after quote acceptance",
    source: "simulated" as const,
  },
  {
    id: "sim_metro_health",
    caseCode: "SIM-METRO-003",
    title: "Metro Health — Claim Settlement Review",
    clientCompanyName: "Metro Health",
    brokerName: "CareShield Brokers",
    insuranceType: "Health Claim",
    currentTeam: "claims",
    currentBlockName: "Surveyor Report Review",
    currentStatus: "IN_PROGRESS",
    expectedPremium: "₹9L",
    monthEndPriority: false,
    businessImpact: "Claim closure awaiting surveyor confirmation",
    source: "simulated" as const,
  },
];

export const simulatedExternalIssues = [
  {
    id: "sim_ext_fire_certificate",
    requestType: "BROKER_DOCUMENT_RESPONSE",
    title: "Broker uploaded Fire Safety Certificate",
    brokerName: "Apex Risk Brokers",
    ownerTeam: "sales",
    status: "REVIEW_PENDING",
    managerObservationRequired: true,
    description:
      "Broker has uploaded the missing Fire Safety Certificate. Sales must verify and forward cleanly to Underwriting.",
    salesDecision: "PENDING_REVIEW",
    priority: "HIGH",
    source: "simulated" as const,
  },
  {
    id: "sim_ext_stock_value",
    requestType: "BROKER_CLARIFICATION",
    title: "Stock value mismatch clarification",
    brokerName: "MetroSure Brokers",
    ownerTeam: "underwriting",
    status: "FORWARDED_INTERNALLY",
    managerObservationRequired: true,
    description:
      "Broker clarified stock value mismatch. Underwriting observation is required before Pricing can continue.",
    salesDecision: "FORWARDED_TO_UNDERWRITING",
    priority: "HIGH",
    source: "simulated" as const,
  },
];

export const simulatedTeamSummary = [
  {
    team: "sales",
    label: "Sales",
    waiting: 4,
    inProgress: 1,
    blocked: 0,
    completed: 1,
  },
  {
    team: "underwriting",
    label: "Underwriting",
    waiting: 8,
    inProgress: 0,
    blocked: 1,
    completed: 0,
  },
  {
    team: "pricing",
    label: "Pricing",
    waiting: 7,
    inProgress: 0,
    blocked: 0,
    completed: 0,
  },
  {
    team: "finance",
    label: "Finance",
    waiting: 6,
    inProgress: 0,
    blocked: 1,
    completed: 0,
  },
  {
    team: "policyIssuance",
    label: "Policy Issuance",
    waiting: 6,
    inProgress: 0,
    blocked: 1,
    completed: 0,
  },
  {
    team: "claims",
    label: "Claims",
    waiting: 1,
    inProgress: 0,
    blocked: 0,
    completed: 0,
  },
  {
    team: "management",
    label: "Management",
    waiting: 3,
    inProgress: 0,
    blocked: 0,
    completed: 0,
  },
];